In [0]:
import numpy as np
import pandas as pd

In [0]:
data = pd.read_csv('bbc-text.csv')

In [3]:
data.head(10)

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...
5       politics  howard hits back at mongrel jibe michael howar...
6       politics  blair prepares to name poll date tony blair is...
7          sport  henman hopes ended in dubai third seed tim hen...
8          sport  wilkinson fit to face edinburgh england captai...
9  entertainment  last star wars  not for children  the sixth an...

In [4]:
data.describe()

category                                               text
count      2225                                               2225
unique        5                                               2126
top       sport  apple unveils low-cost  mac mini  apple has un...
freq        511                                                  2

In [5]:
import re
from nltk.tokenize import word_tokenize  
from nltk.stem import PorterStemmer 
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
regex = re.compile('[^a-zA-Z]')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [0]:
for i in range(len(data['text'])): 
    new_article = ''
    article = word_tokenize(data['text'][i]) 
    for word in article :
        word = regex.sub('', word)
        word = word.lower() 
        word = ps.stem(word) 
        if word not in stop_words and len(word)>1 and word.isalpha(): 
            new_article = new_article + word + ' '
    data['text'][i] = new_article

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
kelas = list(data['category'].unique())
le.fit(kelas)
data['category'] = le.transform(data['category'])

In [8]:
data.head()

category                                               text
0         4  tv futur hand viewer home theatr system plasma...
1         0  worldcom boss left book alon former worldcom b...
2         3  tiger wari farrel gambl leicest say rush make ...
3         3  yead face newcastl fa cup premiership side new...
4         1  ocean twelv raid box offic ocean twelv crime c...

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [10]:
matriks_vector = vectorizer.fit_transform(data['text'])
print(matriks_vector.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
vectorizer.get_feature_names()

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(matriks_vector,data['category'], test_size=0.33, random_state=1)

In [13]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train.toarray(), y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [14]:
y_pred = clf.predict(X_test.toarray())
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred)*100,"%")

92.10884353741497 %


In [15]:
from sklearn.model_selection import cross_val_score
print(max(cross_val_score(clf, matriks_vector.toarray(),data['category'], cv=15))*100,"%")

96.64429530201343 %
